/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.index.engine;

import org.apache.lucene.util.BytesRef;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.mapper.ParsedDocument;
import org.elasticsearch.sourcebatch.SourceBatch;
import org.elasticsearch.xcontent.XContentType;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static org.elasticsearch.index.seqno.SequenceNumbers.UNASSIGNED_PRIMARY_TERM;
import static org.elasticsearch.index.seqno.SequenceNumbers.UNASSIGNED_SEQ_NO;

/**
 * A flattened (columnar) view of one batch of engine operations, paired with the
 * {@link SourceBatch} carrying the user-supplied document sources for that batch.
 *
 * <p>Rather than a {@code List<Engine.Index>} of rich per-operation objects, every scalar
 * operation characteristic (seqNo, version, uid, routing, ...) lives in its own parallel
 * array, one slot per operation. This is cheap to iterate — walking the batch to build a
 * {@link org.elasticsearch.index.translog.Translog.IndexBatch} record is a straight array
 * scan rather than a per-object field extraction — and cheap to serialize, since the arrays
 * already mirror the shape of {@link org.elasticsearch.index.translog.Translog.IndexBatch.Op}.
 *
 * <p>A slot is either an index operation or a no-op. No-op slots exist so this type can
 * eventually represent recovery batches, where a persisted
 * {@link org.elasticsearch.index.translog.Translog.IndexBatch} may decode to a mix of index
 * and no-op entries; {@link #explode()} is the sequential fallback for consumers (such as a
 * future batched recovery path) that are not yet batch-aware.
 *
 * <p>Every operation in a batch shares the same {@link Engine.Operation.Origin} and primary
 * term; this is enforced when the batch is built.
 *
 * <p>The Lucene document needed to index or update a slot is kept in a {@code ParsedDocument[]}
 * sidecar rather than flattened, since building a Lucene {@code Document} is inherently
 * per-row work. This sidecar is expected to be replaced by a columnar document representation
 * in the future; the flattened scalar arrays and the engine-to-translog plumbing built around
 * them are not affected by that change.
 *
 * <p>This class does not own {@link #source()}; the caller that owns the incoming
 * {@link SourceBatch} remains responsible for closing it.
 */
public final class EngineBatch {

    private final Engine.Operation.Origin origin;
    private final long primaryTerm;

    private final boolean[] noOp;
    private final BytesRef[] uids;
    private final long[] seqNos;
    private final long[] versions;
    private final VersionType[] versionTypes;
    private final long[] startTimes;
    private final long[] autoGeneratedIdTimestamps;
    private final boolean[] isRetry;
    // null when no operation in the batch uses compare-and-swap (if_seq_no/if_primary_term), which is the common
    // case; ifSeqNo(int)/ifPrimaryTerm(int) fall back to the unassigned sentinels when these are null.
    private final long[] ifSeqNos;
    private final long[] ifPrimaryTerms;
    private final String[] routings;
    private final XContentType[] xContentTypes;
    private final String[] reasons;
    private final ParsedDocument[] parsedDocs;

    private final SourceBatch source;

    EngineBatch(
        Engine.Operation.Origin origin,
        long primaryTerm,
        boolean[] noOp,
        BytesRef[] uids,
        long[] seqNos,
        long[] versions,
        VersionType[] versionTypes,
        long[] startTimes,
        long[] autoGeneratedIdTimestamps,
        boolean[] isRetry,
        long[] ifSeqNos,
        long[] ifPrimaryTerms,
        String[] routings,
        XContentType[] xContentTypes,
        String[] reasons,
        ParsedDocument[] parsedDocs,
        SourceBatch source
    ) {
        final int size = noOp.length;
        assert uids.length == size
            && seqNos.length == size
            && versions.length == size
            && versionTypes.length == size
            && startTimes.length == size
            && autoGeneratedIdTimestamps.length == size
            && isRetry.length == size
            && (ifSeqNos == null || ifSeqNos.length == size)
            && (ifPrimaryTerms == null || ifPrimaryTerms.length == size)
            && routings.length == size
            && xContentTypes.length == size
            && reasons.length == size
            && parsedDocs.length == size : "all per-slot arrays must have the same length";
        this.origin = Objects.requireNonNull(origin, "origin");
        this.primaryTerm = primaryTerm;
        this.noOp = noOp;
        this.uids = uids;
        this.seqNos = seqNos;
        this.versions = versions;
        this.versionTypes = versionTypes;
        this.startTimes = startTimes;
        this.autoGeneratedIdTimestamps = autoGeneratedIdTimestamps;
        this.isRetry = isRetry;
        this.ifSeqNos = ifSeqNos;
        this.ifPrimaryTerms = ifPrimaryTerms;
        this.routings = routings;
        this.xContentTypes = xContentTypes;
        this.reasons = reasons;
        this.parsedDocs = parsedDocs;
        this.source = Objects.requireNonNull(source, "source");
    }

    /**
     * Builds an all-index-operation batch from a {@code List<Engine.Index>} and its paired
     * {@link SourceBatch}, flattening every operation's scalar characteristics into parallel
     * arrays. Validates that {@code operations} maps 1:1 to {@code source}'s rows and that
     * every operation shares the same origin and primary term, folding in the checks
     * previously performed ad hoc by {@code InternalEngine#indexBatch}/{@code processSubBatch}.
     */
    public static EngineBatch fromIndexOperations(List<Engine.Index> operations, SourceBatch source) {
        final int size = operations.size();
        if (size != source.docCount()) {
            throw new IllegalArgumentException("operations [" + size + "] must map 1:1 to batch rows [" + source.docCount() + "]");
        }
        if (size == 0) {
            throw new IllegalArgumentException("a batch must contain at least one operation");
        }
        final Engine.Index first = operations.get(0);
        final Engine.Operation.Origin origin = first.origin();
        final long primaryTerm = first.primaryTerm();

        // Compare-and-swap (if_seq_no/if_primary_term) is rare and never reaches the translog; only
        // allocate the two CAS arrays when at least one operation in the batch actually uses it.
        boolean anyCas = false;
        for (Engine.Index op : operations) {
            if (op.getIfSeqNo() != UNASSIGNED_SEQ_NO || op.getIfPrimaryTerm() != UNASSIGNED_PRIMARY_TERM) {
                anyCas = true;
                break;
            }
        }

        final boolean[] noOp = new boolean[size];
        final BytesRef[] uids = new BytesRef[size];
        final long[] seqNos = new long[size];
        final long[] versions = new long[size];
        final VersionType[] versionTypes = new VersionType[size];
        final long[] startTimes = new long[size];
        final long[] autoGeneratedIdTimestamps = new long[size];
        final boolean[] isRetry = new boolean[size];
        final long[] ifSeqNos = anyCas ? new long[size] : null;
        final long[] ifPrimaryTerms = anyCas ? new long[size] : null;
        final String[] routings = new String[size];
        final XContentType[] xContentTypes = new XContentType[size];
        final String[] reasons = new String[size];
        final ParsedDocument[] parsedDocs = new ParsedDocument[size];

        for (int i = 0; i < size; i++) {
            final Engine.Index op = operations.get(i);
            if (op.origin() != origin) {
                final var message = "mixed origins in batch: " + origin + " vs " + op.origin();
                assert false : message;
                throw new IllegalStateException(message);
            }
            if (op.primaryTerm() != primaryTerm) {
                final var message = "mixed primary terms in batch: " + primaryTerm + " vs " + op.primaryTerm();
                assert false : message;
                throw new IllegalStateException(message);
            }
            uids[i] = op.uid();
            seqNos[i] = op.seqNo();
            versions[i] = op.version();
            versionTypes[i] = op.versionType();
            startTimes[i] = op.startTime();
            autoGeneratedIdTimestamps[i] = op.getAutoGeneratedIdTimestamp();
            isRetry[i] = op.isRetry();
            if (anyCas) {
                ifSeqNos[i] = op.getIfSeqNo();
                ifPrimaryTerms[i] = op.getIfPrimaryTerm();
            }
            routings[i] = op.routing();
            xContentTypes[i] = op.parsedDoc().getXContentType();
            parsedDocs[i] = op.parsedDoc();
        }

        return new EngineBatch(
            origin,
            primaryTerm,
            noOp,
            uids,
            seqNos,
            versions,
            versionTypes,
            startTimes,
            autoGeneratedIdTimestamps,
            isRetry,
            ifSeqNos,
            ifPrimaryTerms,
            routings,
            xContentTypes,
            reasons,
            parsedDocs,
            source
        );
    }

    /** The number of slots (operations) in this batch. */
    public int size() {
        return noOp.length;
    }

    /** The origin shared by every operation in this batch. */
    public Engine.Operation.Origin origin() {
        return origin;
    }

    /** The primary term shared by every operation in this batch. */
    public long primaryTerm() {
        return primaryTerm;
    }

    /** The user-supplied document sources for this batch. Not owned by this object. */
    public SourceBatch source() {
        return source;
    }

    /** A non-owning view of {@link #source()} covering rows {@code [from, to)}. */
    public SourceBatch sourceSlice(int from, int to) {
        return source.slice(from, to);
    }

    /** Whether slot {@code i} is a no-op rather than an index operation. */
    public boolean isNoOp(int i) {
        return noOp[i];
    }

    public BytesRef uid(int i) {
        return uids[i];
    }

    public long seqNo(int i) {
        return seqNos[i];
    }

    /** Assigns the sequence number for slot {@code i}, e.g. once reserved for a primary operation. */
    public void setSeqNo(int i, long seqNo) {
        seqNos[i] = seqNo;
    }

    public long version(int i) {
        return versions[i];
    }

    public VersionType versionType(int i) {
        return versionTypes[i];
    }

    public long startTime(int i) {
        return startTimes[i];
    }

    public long autoGeneratedIdTimestamp(int i) {
        return autoGeneratedIdTimestamps[i];
    }

    public boolean isRetry(int i) {
        return isRetry[i];
    }

    public long ifSeqNo(int i) {
        return ifSeqNos == null ? UNASSIGNED_SEQ_NO : ifSeqNos[i];
    }

    public long ifPrimaryTerm(int i) {
        return ifPrimaryTerms == null ? UNASSIGNED_PRIMARY_TERM : ifPrimaryTerms[i];
    }

    public String routing(int i) {
        return routings[i];
    }

    public XContentType xContentType(int i) {
        return xContentTypes[i];
    }

    /** The no-op reason for slot {@code i}; only meaningful when {@link #isNoOp(int)} is {@code true}. */
    public String reason(int i) {
        return reasons[i];
    }

    /** The Lucene document sidecar for slot {@code i}; only meaningful for index slots. */
    public ParsedDocument parsedDoc(int i) {
        return parsedDocs[i];
    }

    /**
     * Reconstructs the {@link Engine.Index} for slot {@code i} from the flattened arrays and
     * the {@link ParsedDocument} sidecar. This is the bridge that lets the existing per-operation
     * indexing-strategy planning and Lucene-write code (which is unchanged by this batch
     * representation) keep operating on {@link Engine.Index} objects.
     *
     * @throws IllegalStateException if slot {@code i} is a no-op
     */
    public Engine.Index materializeIndex(int i) {
        if (noOp[i]) {
            throw new IllegalStateException("slot [" + i + "] is a no-op, not an index operation");
        }
        return new Engine.Index(
            uids[i],
            parsedDocs[i],
            seqNos[i],
            primaryTerm,
            versions[i],
            versionTypes[i],
            origin,
            startTimes[i],
            autoGeneratedIdTimestamps[i],
            isRetry[i],
            ifSeqNo(i),
            ifPrimaryTerm(i)
        );
    }

    /**
     * Sequentially materializes every slot back into an {@link Engine.Operation}: index slots
     * via {@link #materializeIndex(int)}, no-op slots as an {@link Engine.NoOp}. This is the
     * fallback for consumers not yet able to process an {@link EngineBatch} directly, mirroring
     * how {@code Translog.IndexBatch#explode()} turns a persisted batch back into individual
     * translog operations.
     */
    public List<Engine.Operation> explode() {
        final List<Engine.Operation> operations = new ArrayList<>(size());
        for (int i = 0; i < size(); i++) {
            if (noOp[i]) {
                operations.add(new Engine.NoOp(seqNos[i], primaryTerm, origin, startTimes[i], reasons[i]));
            } else {
                operations.add(materializeIndex(i));
            }
        }
        return operations;
    }
}
