/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.index.engine;

import org.apache.lucene.util.BytesRef;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.eirf.EirfEncoder;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.mapper.ParsedDocument;
import org.elasticsearch.index.mapper.Uid;
import org.elasticsearch.sourcebatch.SourceBatch;
import org.elasticsearch.test.ESTestCase;
import org.elasticsearch.xcontent.XContentType;

import java.io.IOException;
import java.util.List;

import static org.elasticsearch.index.seqno.SequenceNumbers.UNASSIGNED_PRIMARY_TERM;
import static org.elasticsearch.index.seqno.SequenceNumbers.UNASSIGNED_SEQ_NO;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;
import static org.hamcrest.Matchers.sameInstance;

public class EngineBatchTests extends ESTestCase {

    private static Engine.Index primaryIndexOp(
        String id,
        long seqNo,
        long version,
        long autoGeneratedIdTimestamp,
        boolean isRetry,
        long ifSeqNo,
        long ifPrimaryTerm,
        long primaryTerm,
        long startTime
    ) {
        final ParsedDocument doc = EngineTestCase.createParsedDoc(id, null);
        return new Engine.Index(
            Uid.encodeId(id),
            doc,
            seqNo,
            primaryTerm,
            version,
            VersionType.INTERNAL,
            Engine.Operation.Origin.PRIMARY,
            startTime,
            autoGeneratedIdTimestamp,
            isRetry,
            ifSeqNo,
            ifPrimaryTerm
        );
    }

    private static SourceBatch encodeSources(List<Engine.Index> operations) throws IOException {
        final List<BytesReference> sources = operations.stream().map(op -> op.source().originalBytes()).toList();
        final XContentType xContentType = operations.get(0).parsedDoc().getXContentType();
        return EirfEncoder.encode(sources, xContentType);
    }

    public void testFromIndexOperationsFlattensFields() throws IOException {
        final Engine.Index op1 = primaryIndexOp("id-1", 3, 10, 111L, true, 1, 7, 5, 1000L);
        final Engine.Index op2 = primaryIndexOp("id-2", 4, 11, -1L, false, UNASSIGNED_SEQ_NO, UNASSIGNED_PRIMARY_TERM, 5, 2000L);
        final List<Engine.Index> operations = List.of(op1, op2);

        try (SourceBatch source = encodeSources(operations)) {
            final EngineBatch batch = EngineBatch.fromIndexOperations(operations, source);

            assertThat(batch.size(), equalTo(2));
            assertThat(batch.origin(), equalTo(Engine.Operation.Origin.PRIMARY));
            assertThat(batch.primaryTerm(), equalTo(5L));
            assertThat(batch.source(), sameInstance(source));

            assertFlattenedFieldsMatch(batch, 0, op1);
            assertFlattenedFieldsMatch(batch, 1, op2);
        }
    }

    private static void assertFlattenedFieldsMatch(EngineBatch batch, int i, Engine.Index op) {
        assertFalse(batch.isNoOp(i));
        assertThat(batch.uid(i), equalTo(op.uid()));
        assertThat(batch.seqNo(i), equalTo(op.seqNo()));
        assertThat(batch.version(i), equalTo(op.version()));
        assertThat(batch.versionType(i), equalTo(op.versionType()));
        assertThat(batch.startTime(i), equalTo(op.startTime()));
        assertThat(batch.autoGeneratedIdTimestamp(i), equalTo(op.getAutoGeneratedIdTimestamp()));
        assertThat(batch.isRetry(i), equalTo(op.isRetry()));
        assertThat(batch.ifSeqNo(i), equalTo(op.getIfSeqNo()));
        assertThat(batch.ifPrimaryTerm(i), equalTo(op.getIfPrimaryTerm()));
        assertThat(batch.routing(i), equalTo(op.routing()));
        assertThat(batch.xContentType(i), equalTo(op.parsedDoc().getXContentType()));
        assertThat(batch.parsedDoc(i), sameInstance(op.parsedDoc()));
    }

    public void testFromIndexOperationsRejectsSizeMismatch() throws IOException {
        final Engine.Index op = primaryIndexOp("id-1", UNASSIGNED_SEQ_NO, 1, -1L, false, UNASSIGNED_SEQ_NO, UNASSIGNED_PRIMARY_TERM, 1, 0L);
        final List<Engine.Index> operations = List.of(op);
        try (SourceBatch source = encodeSources(operations); SourceBatch empty = source.slice(0, 0)) {
            expectThrows(IllegalArgumentException.class, () -> EngineBatch.fromIndexOperations(operations, empty));
        }
    }

    public void testFromIndexOperationsRejectsMixedOrigin() throws IOException {
        final ParsedDocument doc1 = EngineTestCase.createParsedDoc("id-1", null);
        final ParsedDocument doc2 = EngineTestCase.createParsedDoc("id-2", null);
        final Engine.Index primary = new Engine.Index(
            Uid.encodeId("id-1"),
            doc1,
            UNASSIGNED_SEQ_NO,
            1,
            1,
            VersionType.INTERNAL,
            Engine.Operation.Origin.PRIMARY,
            0L,
            -1L,
            false,
            UNASSIGNED_SEQ_NO,
            UNASSIGNED_PRIMARY_TERM
        );
        final Engine.Index replica = new Engine.Index(
            Uid.encodeId("id-2"),
            doc2,
            5,
            1,
            1,
            null,
            Engine.Operation.Origin.REPLICA,
            0L,
            -1L,
            false,
            UNASSIGNED_SEQ_NO,
            UNASSIGNED_PRIMARY_TERM
        );
        final List<Engine.Index> operations = List.of(primary, replica);
        try (SourceBatch source = encodeSources(operations)) {
            expectThrows(AssertionError.class, () -> EngineBatch.fromIndexOperations(operations, source));
        }
    }

    public void testFromIndexOperationsRejectsMixedPrimaryTerm() throws IOException {
        final Engine.Index op1 = primaryIndexOp(
            "id-1",
            UNASSIGNED_SEQ_NO,
            1,
            -1L,
            false,
            UNASSIGNED_SEQ_NO,
            UNASSIGNED_PRIMARY_TERM,
            1,
            0L
        );
        final Engine.Index op2 = primaryIndexOp(
            "id-2",
            UNASSIGNED_SEQ_NO,
            1,
            -1L,
            false,
            UNASSIGNED_SEQ_NO,
            UNASSIGNED_PRIMARY_TERM,
            2,
            0L
        );
        final List<Engine.Index> operations = List.of(op1, op2);
        try (SourceBatch source = encodeSources(operations)) {
            expectThrows(AssertionError.class, () -> EngineBatch.fromIndexOperations(operations, source));
        }
    }

    public void testIfSeqNoAndIfPrimaryTermDefaultWhenNoOperationUsesCas() throws IOException {
        final Engine.Index op1 = primaryIndexOp(
            "id-1",
            UNASSIGNED_SEQ_NO,
            1,
            -1L,
            false,
            UNASSIGNED_SEQ_NO,
            UNASSIGNED_PRIMARY_TERM,
            1,
            0L
        );
        final Engine.Index op2 = primaryIndexOp(
            "id-2",
            UNASSIGNED_SEQ_NO,
            1,
            -1L,
            false,
            UNASSIGNED_SEQ_NO,
            UNASSIGNED_PRIMARY_TERM,
            1,
            0L
        );
        final List<Engine.Index> operations = List.of(op1, op2);
        try (SourceBatch source = encodeSources(operations)) {
            final EngineBatch batch = EngineBatch.fromIndexOperations(operations, source);

            assertThat(batch.ifSeqNo(0), equalTo(UNASSIGNED_SEQ_NO));
            assertThat(batch.ifPrimaryTerm(0), equalTo(UNASSIGNED_PRIMARY_TERM));
            assertThat(batch.ifSeqNo(1), equalTo(UNASSIGNED_SEQ_NO));
            assertThat(batch.ifPrimaryTerm(1), equalTo(UNASSIGNED_PRIMARY_TERM));
        }
    }

    public void testMaterializeIndexRoundTrips() throws IOException {
        final Engine.Index op = primaryIndexOp("id-1", 3, 10, 111L, true, 1, 7, 5, 1000L);
        final List<Engine.Index> operations = List.of(op);
        try (SourceBatch source = encodeSources(operations)) {
            final EngineBatch batch = EngineBatch.fromIndexOperations(operations, source);
            final Engine.Index materialized = batch.materializeIndex(0);

            assertThat(materialized.uid(), equalTo(op.uid()));
            assertThat(materialized.seqNo(), equalTo(op.seqNo()));
            assertThat(materialized.primaryTerm(), equalTo(op.primaryTerm()));
            assertThat(materialized.version(), equalTo(op.version()));
            assertThat(materialized.versionType(), equalTo(op.versionType()));
            assertThat(materialized.origin(), equalTo(op.origin()));
            assertThat(materialized.startTime(), equalTo(op.startTime()));
            assertThat(materialized.getAutoGeneratedIdTimestamp(), equalTo(op.getAutoGeneratedIdTimestamp()));
            assertThat(materialized.isRetry(), equalTo(op.isRetry()));
            assertThat(materialized.getIfSeqNo(), equalTo(op.getIfSeqNo()));
            assertThat(materialized.getIfPrimaryTerm(), equalTo(op.getIfPrimaryTerm()));
            assertThat(materialized.id(), equalTo(op.id()));
            assertThat(materialized.parsedDoc(), sameInstance(op.parsedDoc()));
        }
    }

    public void testSetSeqNoMutatesSeqNoAndMaterializedIndex() throws IOException {
        final Engine.Index op = primaryIndexOp("id-1", UNASSIGNED_SEQ_NO, 1, -1L, false, UNASSIGNED_SEQ_NO, UNASSIGNED_PRIMARY_TERM, 1, 0L);
        final List<Engine.Index> operations = List.of(op);
        try (SourceBatch source = encodeSources(operations)) {
            final EngineBatch batch = EngineBatch.fromIndexOperations(operations, source);
            batch.setSeqNo(0, 42);

            assertThat(batch.seqNo(0), equalTo(42L));
            assertThat(batch.materializeIndex(0).seqNo(), equalTo(42L));
        }
    }

    public void testExplodeMixOfIndexAndNoOpSlots() throws IOException {
        final Engine.Index indexOp = primaryIndexOp("id-1", 3, 10, -1L, false, UNASSIGNED_SEQ_NO, UNASSIGNED_PRIMARY_TERM, 5, 1000L);
        try (SourceBatch source = encodeSources(List.of(indexOp))) {
            final boolean[] noOp = new boolean[] { false, true };
            final BytesRef[] uids = new BytesRef[] { indexOp.uid(), null };
            final long[] seqNos = new long[] { indexOp.seqNo(), 99L };
            final long[] versions = new long[] { indexOp.version(), 0L };
            final VersionType[] versionTypes = new VersionType[] { indexOp.versionType(), null };
            final long[] startTimes = new long[] { indexOp.startTime(), 12345L };
            final long[] autoGeneratedIdTimestamps = new long[] { indexOp.getAutoGeneratedIdTimestamp(), -1L };
            final boolean[] isRetry = new boolean[] { indexOp.isRetry(), false };
            final long[] ifSeqNos = new long[] { indexOp.getIfSeqNo(), UNASSIGNED_SEQ_NO };
            final long[] ifPrimaryTerms = new long[] { indexOp.getIfPrimaryTerm(), UNASSIGNED_PRIMARY_TERM };
            final String[] routings = new String[] { indexOp.routing(), null };
            final XContentType[] xContentTypes = new XContentType[] { indexOp.parsedDoc().getXContentType(), null };
            final String[] reasons = new String[] { null, "recovered no-op" };
            final ParsedDocument[] parsedDocs = new ParsedDocument[] { indexOp.parsedDoc(), null };

            final EngineBatch batch = new EngineBatch(
                Engine.Operation.Origin.PRIMARY,
                5,
                noOp,
                uids,
                seqNos,
                versions,
                versionTypes,
                startTimes,
                autoGeneratedIdTimestamps,
                isRetry,
                ifSeqNos,
                ifPrimaryTerms,
                routings,
                xContentTypes,
                reasons,
                parsedDocs,
                source
            );

            assertFalse(batch.isNoOp(0));
            assertTrue(batch.isNoOp(1));
            expectThrows(IllegalStateException.class, () -> batch.materializeIndex(1));

            final List<Engine.Operation> exploded = batch.explode();
            assertThat(exploded.size(), equalTo(2));
            assertThat(exploded.get(0), instanceOf(Engine.Index.class));
            final Engine.Index explodedIndex = (Engine.Index) exploded.get(0);
            assertThat(explodedIndex.id(), equalTo(indexOp.id()));
            assertThat(explodedIndex.seqNo(), equalTo(indexOp.seqNo()));

            assertThat(exploded.get(1), instanceOf(Engine.NoOp.class));
            final Engine.NoOp explodedNoOp = (Engine.NoOp) exploded.get(1);
            assertThat(explodedNoOp.seqNo(), equalTo(99L));
            assertThat(explodedNoOp.primaryTerm(), equalTo(5L));
            assertThat(explodedNoOp.origin(), equalTo(Engine.Operation.Origin.PRIMARY));
            assertThat(explodedNoOp.startTime(), equalTo(12345L));
            assertThat(explodedNoOp.reason(), equalTo("recovered no-op"));
        }
    }
}
